### ISSUE TITLE
get_markdown() and get_html() return NULL on first call

### ISSUE THREAD

**Issue by gordon-turner** [jdtrat/shinymarkdown#3]
Fantastic package!  Just what I'm looking for.  Thank you for working on this 👍 

get_markdown() and get_html() seem to need two calls to return the contents.  First call returns NULL, second call returns the contents.  

If you then edit the contents in the editor, the next call returns the previous contents, and then a second call after that returns the latest contents.

**Comment by jdtrat** [comment]
Hi Gordon! Thanks so much. I'm glad you have a use-case for this 😄!

I just overhauled the package to make it more like a traditional Shiny input. Please check out the [new documentation](https://github.com/jdtrat/shinymarkdown#accessing-the-editors-contents) and let me know if that works for you! 

If you have any feedback on the documentation or general structure, please let me know!

**Comment by gordon-turner** [comment]
Wow that works great!  I love that you can just access the markdown like a regular reactive value.  Thanks for such a quick fix!
